[package]
name = "layered-nft-gen"
version = "0.1.0"
edition = "2024"
default-run = "layered-nft-gen"

[dependencies]
image = "0.25"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
walkdir = "2.5"
rayon = "1.8"
oxipng = "9"
